name: Release Camunda Community Project on Maven Central
description: Encapsulates the release process of Camunda community extensions
inputs:
  artifacts-pattern:
    description: Which artifacts to store. Set to empty string to disable.
    required: false
    default: ./target/nexus-staging/**/*.jar
  run-tests:
    default: ""
    required: false
    description: Wether to explicitly run maven tests prior to releasing
  maven-release-options:
    description: Any extra Maven options for the release process (-DskipTests is already implied)
    required: false
    default: "mvn -B ${{ maven-additional-options }} package ${SKIP_TESTS}"
  release-version:
    description: Release Version (usually tag name). If empty, a SNAPSHOT (with the currently configured version) will be deployed.
    required: false
  release-profile:
    description: Maven profile to be selected for the release; typically "release".
    required: false
  nexus-usr:
    description: Camunda Nexus username
    required: true
  nexus-psw:
    description: Camunda Nexus password
    required: true
  maven-usr:
    description: Maven Central username
    required: true
  maven-psw:
    description: Maven Central password
    required: true
  maven-gpg-passphrase:
    description: GPG passphrase used to unlock the signing key
    required: true
  github-token:
    description: GitHub token
    required: true
outputs:
  artifacts_archive_path:
    description: Filename of zipfile containing all files matched by artifacts-pattern.
    value: ${{ steps.create-archive.outputs.filename }}
runs:
  using: composite
  steps:
    - name: Initialize
      run: |-
        echo Repo: ${GITHUB_REPOSITORY}
        git config --global user.name "Release Bot"
        git config --global user.email actions@github.com
        test -n "${{inputs.release-profile}}" && echo 'RELEASE_PROFILE=-P${{inputs.release-profile}}' >> $GITHUB_ENV
        cp -v ${{ github.action_path }}/resources/settings.xml $HOME/.m2/
      shell: bash
    - name: Run maven
      run: |-
        test -z "${{ inputs.run-tests }}" && SKIP_TESTS="-DskipTests"
      shell: bash
    - name: Publish SNAPSHOT
      run: |-
        test -n "${{ inputs.release-version }}" && echo "::debug::Not publishing SNAPSHOT because release-version is set" && exit 0
        mvn -B -DskipTests ${{ inputs.maven-release-options }} deploy
        sed -i 's@:camunda-nexus:.*$@:central:https://oss.sonatype.org/content/repositories/snapshots/@g' target/nexus-staging/deferred/.index
        mvn -B -DskipTests ${{ inputs.maven-release-options }} org.sonatype.plugins:nexus-staging-maven-plugin:deploy-staged
      shell: bash
      env:
        NEXUS_USR: ${{ inputs.nexus-usr}}
        NEXUS_PSW: ${{ inputs.nexus-psw }}
        MAVEN_USR: ${{ inputs.maven-usr }}
        MAVEN_PSW: ${{ inputs.maven-psw }}
    - name: Publish Maven Release
      run: |-
        test -z "${{ inputs.release-version }}" && echo "::debug::Skipping Release because release-version is unset" && exit 0
        # 1. set version
        mvn -B versions:set org.codehaus.mojo:versions-maven-plugin:2.8.1:update-child-modules -DnewVersion=${{ inputs.release-version }}
        # 2. perform release
        mvn -B ${RELEASE_PROFILE} ${{ inputs.maven-release-options }} -DskipTests -DnexusUrl=https://oss.sonatype.org/ -DserverId=central -Drelease-version=${{ inputs.release-version }} -Dgpg.sign initialize \
          package source:jar javadoc:jar \
          deploy org.apache.maven.plugins:maven-gpg-plugin:sign \
          nexus-staging:deploy
      shell: bash
      env:
        NEXUS_USR: ${{ inputs.nexus-usr}}
        NEXUS_PSW: ${{ inputs.nexus-psw }}
        MAVEN_USR: ${{ inputs.maven-usr }}
        MAVEN_PSW: ${{ inputs.maven-psw }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.maven-gpg-passphrase }}
    - name: Prepare next development version
      run: ${{ github.action_path }}/resources/prepare-next-development-version.sh "${{ github.event.repository.default_branch }}" "${{ inputs.release-version }}"
      shell: bash
    - name: Archive artifacts
      run: |-
        test -z "${{ inputs.artifacts-pattern }}" && echo "::debug::Skipping archiving because artifacts-pattern is unset" && exit 0
        # Filename: [repo without org]-[version].zip
        ZIPFILE=${GITHUB_REPOSITORY#*/}-${{ inputs.release-version }}.zip
        zip $ZIPFILE $(find . -path ${{ inputs.artifacts-pattern }})
        echo "::set-output name=filename::${ZIPFILE}"
      shell: bash
      id: create-archive
